# Generated by Django 3.2.6 on 2021-10-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('useremail', models.CharField(max_length=200)),
                ('userpassword', models.CharField(max_length=8)),
                ('imageuser', models.ImageField(blank=True, default='', upload_to='')),
            ],
        ),
    ]
