# Generated by Django 3.2.6 on 2021-10-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imageuser',
        ),
    ]
