# Generated by Django 3.2.6 on 2021-10-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='useremail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userpassword',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
