# Generated by Django 3.2.6 on 2021-10-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211002_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
