# Generated by Django 3.2.6 on 2021-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('useremail', models.CharField(max_length=200, null=True)),
                ('userpassword', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
